name: YAC Python Package CI

on:
  push:
    branches:
      - main
      - package
  pull_request:
    branches:
      - main
      - package

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests argparse

    - name: Run Tests
      run: |
        pytest --cov=yac

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install flake8 for linting
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run Linter
      run: |
        flake8 yac --count --max-complexity=10 --max-line-length=127 --statistics

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: |
        python -m build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: YAC-dist
        path: dist/
